src/Entity/VideoGame.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoGameRepository")
 */

class VideoGame
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $Support;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $description;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateRelease;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Editor", inversedBy="videoGames")
     * @ORM\JoinColumn(nullable=false)
     */
    private $editor;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSupport(): ?string
    {
        return $this->Support;
    }

    public function setSupport(string $Support): self
    {
        $this->Support = $Support;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateRelease(): ?\DateTimeInterface
    {
        return $this->dateRelease;
    }

    public function setDateRelease(?\DateTimeInterface $dateRelease): self
    {
        $this->dateRelease = $dateRelease;

        return $this;
    }

    public function getEditor(): ?Editor
    {
        return $this->editor;
    }

    public function setEditor(?Editor $editor): self
    {
        $this->editor = $editor;

        return $this;
    }
}

src/Form/VideoGameType.php
<?php

namespace App\Form;

use App\Entity\Editor;
use App\Entity\VideoGame;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoGameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('Support')
            ->add('description')
            ->add('dateRelease')
            ->add('editor', EntityType::class, [
                'class' => Editor::class,
                'choice_label' => function (Editor $editor) {
                    return $editor->getCompanyName();
                }
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => VideoGame::class,
        ]);
    }
}

src/Controller/VideoGameController.php
<?php

namespace App\Controller;

use App\Entity\VideoGame;
use App\Form\Type\TaskType;
use App\Form\VideoGameType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class VideoGameController extends AbstractController
{
    /**
     * @Route("/video_game", name="video-game")
     */
    public function index()
    {
        return $this->render('video_game/index.html.twig', [
            'controller_name' => 'VideoGameController',
        ]);
    }

    /**
     * @Route("/creation_VG", name="creation-VG") 
     * @IsGranted("ROLE_ADMIN")
     */ 
    public function createEditorAction(Request $request)
    {   
        $VG = new VideoGame();   
        $form = $this->createForm(VideoGameType::class, $VG);   
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {  
            $entityManager = $this->getDoctrine()->getManager();       
            $entityManager->persist($VG);       
            $entityManager->flush();
            return $this->redirectToRoute('liste-VG');   
        }
    return $this->render('video_game/creat.html.twig', [       
        'VGForm' => $form->createView(),   
        ]); 
    }

    /**
     * @Route("/liste_VG", name="liste-VG")
     * @IsGranted("ROLE_USER")
     */
    public function listAction()
    {
        $list = $this->getDoctrine()
                    ->getRepository(VideoGame::class)
                    ->findAll();

        return $this->render('video_game/show.html.twig', [
            'list' => $list,
        ]);
    }

    /**
     * @Route("/one_VG", name="one-VG")
     * @IsGranted("ROLE_USER")
     */
    public function listOneAction()
    {
        $id = $_GET['id'];
        $VG = $this->getDoctrine()
                    ->getRepository(VideoGame::class)
                    ->find($id);

        return $this->render('video_game/showOne.html.twig', [
            'VG' => $VG,
        ]);
    }

    /**
     * @Route("/modife_VG", name="modife-VG")
     * @IsGranted("ROLE_ADMIN")
     */
    public function modifeVGAction(Request $request)
    { 
        $id = $_GET['id'];
        $VG = $this->getDoctrine()
                    ->getRepository(VideoGame::class)
                    ->find($id);

        $form = $this->createForm(VideoGameType::class, $VG);   
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {  
            $entityManager = $this->getDoctrine()->getManager();       
            $entityManager->persist($VG);       
            $entityManager->flush();
            return $this->redirectToRoute('liste-VG');   
        }
    return $this->render('video_game/creat.html.twig', [       
        'VGForm' => $form->createView(),   
        ]); 
    }

    /**
     * @Route("/supr_VG", name="supr-VG")
     * @IsGranted("ROLE_ADMIN")
     */
    public function deletAction()
    {
        $id = $_GET['id'];
        $VG = $this->getDoctrine()
                    ->getRepository(VideoGame::class)
                    ->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($VG);
        $em->flush();

        return $this->redirectToRoute('liste-VG');
    }
}

templates/video_game/creat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video Game {% endblock %}

{% block body %}  
{% include 'menu.html.twig' %}
<h1>Video Game: </h1> 
{{ form(VGForm) }}
{% endblock %}

templates/video_game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoGameController!{% endblock %}

{% block body %}
{% include 'menu.html.twig' %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/project/src/Controller/VideoGameController.php'|file_link(0) }}">src/Controller/VideoGameController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/project/templates/video_game/index.html.twig'|file_link(0) }}">templates/video_game/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/video_game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video Game {% endblock %}

{% block body %} 
{% include 'menu.html.twig' %} 
<h1>Video Game : </h1> 
 
{% for VG in list %}
<ul>
    <li>{{ VG.id }}</li>
    <li>{{ VG.title}}</li>
    {% if is_granted('ROLE_USER') %}
    <li><a href="{{ path('one-VG') }}?id={{ VG.id }}">+</a></li>
    {% endif  %}
</ul>
{% endfor %}

{% endblock %}

templates/video_game/showOne.html.twig
{% extends 'base.html.twig' %}

{% block title %}User {% endblock %}

{% block body %}  
{% include 'menu.html.twig' %}
<h1>list user : </h1> 
 
<ul>
    <li>{{ VG.id }}</li>
    <li>{{ VG.title }}</li>
    <li>{{ VG.support }}</li>
    <li>{{ VG.description }}</li>
    <li>{{ VG.dateRelease|date("m/d/Y") }}</li>
    <li>{{ VG.editor.id }}</li
    
    {% if is_granted('ROLE_ADMIN') %}
    <li><a href="{{ path('supr-VG') }}?id={{ VG.id }}">supr</a></li>
    <li><a href="{{ path('modife-VG') }}?id={{ VG.id }}">modife</a></li>
    {% endif %}
</ul>

{% endblock %}